import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#353534',
        'surface-tint': '#ffb4ac',
        'surface-container': '#201f1f',
        'surface-dim': '#131313',
        'primary-container': '#ff544c',
        'secondary-fixed': '#98f994',
        'secondary-fixed-dim': '#7ddc7a',
        'tertiary-fixed': '#ffdeac',
        'tertiary-fixed-dim': '#ffba38',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        secondary: '#7ddc7a',
        tertiary: '#ffba38',
        background: '#131313',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        surface: '#131313',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005313',
        'on-tertiary-fixed': '#281900',
        'on-tertiary-fixed-variant': '#604100',
        'on-primary-fixed': '#410002',
        'on-primary-fixed-variant': '#93000d',
        'on-secondary': '#00390a',
        'on-tertiary': '#432c00',
        'on-error': '#690005',
        'on-primary': '#690006',
        'on-primary-container': '#5c0005',
        'on-secondary-container': '#92f28e',
        'on-tertiary-container': '#3a2600',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#bb171c',
        outline: '#ab8985',
        'outline-variant': '#5b403d',
        'surface-bright': '#393939',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'tertiary-container': '#c08600',
        'secondary-container': '#03711e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '48px',
        'edge-margin': '16px',
        lg: '32px',
        md: '20px',
        base: '8px',
        'touch-target-min': '48px',
        sm: '12px',
        xs: '4px',
      },
      fontFamily: {
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'label-xl': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'data-display': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '14px', fontWeight: '600' }],
        'label-xl': ['14px', { lineHeight: '16px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        'data-display': ['48px', { lineHeight: '48px', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
