import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e8e0df',
        'surface-tint': '#ff544c',
        'surface-container': '#f5f0ef',
        'surface-dim': '#d9d4d3',
        'primary-container': '#ff544c',
        'secondary-fixed': '#2e7d32',
        'secondary-fixed-dim': '#4caf50',
        'tertiary-fixed': '#ff9800',
        'tertiary-fixed-dim': '#ffb74d',
        error: '#d32f2f',
        'error-container': '#ffebee',
        'on-error-container': '#b71c1c',
        secondary: '#4caf50',
        tertiary: '#ff9800',
        background: '#faf7f6',
        'on-background': '#1c1b1b',
        'on-surface': '#1c1b1b',
        surface: '#faf7f6',
        'surface-container-low': '#f0ebe9',
        'surface-container-lowest': '#ebe6e4',
        'surface-container-high': '#ece7e4',
        'surface-container-highest': '#e0d8d6',
        'on-secondary-fixed': '#ffffff',
        'on-secondary-fixed-variant': '#e8f5e9',
        'on-tertiary-fixed': '#ffffff',
        'on-tertiary-fixed-variant': '#fff8e1',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'on-secondary-container': '#e8f5e9',
        'on-tertiary-container': '#fff8e1',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f5f0ef',
        'inverse-primary': '#ff867a',
        outline: '#9e8a87',
        'outline-variant': '#d9d4d3',
        'surface-bright': '#ffffff',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'tertiary-container': '#ffc947',
        'secondary-container': '#a5d6a7',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xl: '48px',
        'edge-margin': '16px',
        lg: '32px',
        md: '20px',
        base: '8px',
        'touch-target-min': '48px',
        sm: '12px',
        xs: '4px',
      },
      fontFamily: {
        'headline-xl': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'label-xl': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'data-display': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '16px', fontWeight: '600' }],
        'label-xl': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'data-display': ['40px', { lineHeight: '44px', letterSpacing: '-0.04em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
